#!/bin/sh
set -efu

PYS=${PYS:-"$(py3versions --supported 2>/dev/null)"}

cd "$AUTOPKGTEST_TMP"

for py in $PYS; do
    echo "=== $py ==="
    $py -c 'import numpy; numpy.test(verbose=2, extra_argv=["--ignore=numpy/core/tests/test_mem_policy.py", "-k not test_limited_api and not test_gen_pyf_no_overwrite and not test_max_rows_empty_lines"])' 2>&1
done
